name: PR Checks

on:
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # match your project's Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run PR checks
        run: ./scripts/pr_checks.sh
